### ISSUE TITLE
Multiples loaders should be both shut down

### ISSUE THREAD

**Issue by Albejr** [haoliangwu/ngx-loading-mask#5]
How to shut down multiple instances of the same loader?

![loader](https://user-images.githubusercontent.com/24717256/38279367-57414e0e-3776-11e8-9000-5b0550e30672.gif)

```
<div class="card" [ngxLoadingMask]="'loaderGroup'">
        <div class="card-content">
          ...
        </div>
  </div>
  <div class="card" [ngxLoadingMask]="'loaderGroup'">
        <div class="card-content">
          ...
        </div>
  </div>
```

**Comment by haoliangwu** [comment]
hi @Albejr ,

thanks for your report, it should be a bug, I'll do fix when I have free time.

**Comment by haoliangwu** [comment]
should be fixed after upgrade module to ``ngx-loading-mask@5.3.2``, thx.

**Comment by Albejr** [comment]
Greate job!
It's works.
