### ISSUE TITLE
Throw Error from api in hideGroupError throw new error

### ISSUE THREAD

**Issue by warinthornS** [haoliangwu/ngx-loading-mask#7]
the method hideGroupError is throw new error  >> result "[object Object]" is not error

**Comment by haoliangwu** [comment]
thx for you suggestion, I has changed the way to give feedback of error, use ``console.error`` rather than throw error directly.

**Comment by haoliangwu** [comment]
should work after eda6aec1b14d6709599e26a6cb56c0eafec933bf or ngx-loading-mask@5.3.3
